title: TGA-STUDY
description: このサイトの管理人が、勉強会やLT、講話などで使用した資料や関連資料をザックリとまとめたページです。元資料のライセンスおよび著作権法の「引用」の範囲内で転載（引用）可です。記事のシェアも歓迎です。
baseurl: "/tga-study"
url: "https://togazo.github.io"
twitter_username: togazo
github_username:  togazo

markdown: kramdown

collections:
    articles:
        output: true

# Exclude from processing.
 exclude:
   - Gemfile
   - Gemfile.lock
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
